#!/bin/bash
# MySkills Protocol - Real Demo Recording Guide
# This script opens all necessary windows for manual recording

set -e

echo "🎬 MySkills Protocol - Real Demo Recording"
echo "=========================================="
echo ""

# Check if OpenClaw Gateway is running
if ! curl -s http://127.0.0.1:18789/health > /dev/null 2>&1; then
    echo "⚠️  OpenClaw Gateway not running at http://127.0.0.1:18789"
    echo "   Please start it first with: cd packages/openclaw-gateway && npm start"
    echo ""
fi

# Create videos directory
mkdir -p videos

echo "📋 Recording Checklist:"
echo ""
echo "Before you start:"
echo "  ✅ OpenClaw Gateway running at http://127.0.0.1:18789/chat"
echo "  ✅ MySkills website accessible at https://myskills2026.ddttupupo.buzz"
echo "  ✅ Wallet with testnet MON ready (for connection demo)"
echo ""
echo "🎥 Recording Instructions:"
echo "  1. Press Cmd+Shift+5 to open screen recording"
echo "  2. Select 'Record Entire Screen' or 'Record Selected Portion'"
echo "  3. Click 'Record'"
echo "  4. Follow the scene-by-scene guide below"
echo "  5. Press stop button when done (after ~90 seconds)"
echo ""
echo "📹 Scene-by-Scene Guide:"
echo ""
echo "┌─────────────────────────────────────────────────────────────────┐"
echo "│ SCENE 1: Website Introduction (0:00-0:15)                       │"
echo "├─────────────────────────────────────────────────────────────────┤"
echo "│ 1. Open https://myskills2026.ddttupupo.buzz                     │"
echo "│ 2. Show homepage with 'Agent Reward Hub'                        │"
echo "│ 3. Scroll down to show skill cards                              │"
echo "│ 4. Highlight '98/2 split' tags                                   │"
echo "│ 5. Show different platform badges (Claude, Coze, Manus, MiniMax) │"
echo "│ 6. Scroll back to top                                            │"
echo "└─────────────────────────────────────────────────────────────────┘"
echo ""
echo "┌─────────────────────────────────────────────────────────────────┐"
echo "│ SCENE 2: Smart Matching Engine (0:15-0:30)                      │"
echo "├─────────────────────────────────────────────────────────────────┤"
echo "│ 1. Find and click 'Smart Matching' or similar                   │"
echo "│ 2. Show the input field for user requests                       │"
echo "│ 3. Show budget slider/input                                     │"
echo "│ 4. Show optimization goal options                               │"
echo "│ 5. Display 'Find Skills' button                                 │"
echo "└─────────────────────────────────────────────────────────────────┘"
echo ""
echo "┌─────────────────────────────────────────────────────────────────┐"
echo "│ SCENE 3: Wallet Connection (0:30-0:45)                          │"
echo "├─────────────────────────────────────────────────────────────────┤"
echo "│ 1. Click 'Connect Wallet' button in top right                   │"
echo "│ 2. Show RainbowKit wallet connection modal                      │"
echo "│ 3. Select a wallet option (show available options)              │"
echo "│ 4. After connection, show truncated address in top right        │"
echo "└─────────────────────────────────────────────────────────────────┘"
echo ""
echo "┌─────────────────────────────────────────────────────────────────┐"
echo "│ SCENE 4: OpenClaw Gateway Demo (0:45-1:10)                      │"
echo "├─────────────────────────────────────────────────────────────────┤"
echo "│ 1. Open http://127.0.0.1:18789/chat in new tab/window           │"
echo "│ 2. Input: '我有一堆小学奥数题的PDF文件，需要自动识别题          │"
echo "│           目、解析公式、整理到我的题库里。谁能帮我？预算5 MON'   │"
echo "│ 3. Show the Smart Matching Engine analyzing the request         │"
echo "│ 4. Display matched skills with scores                            │"
echo "│ 5. Show parallel agent coordination if available                │"
echo "└─────────────────────────────────────────────────────────────────┘"
echo ""
echo "┌─────────────────────────────────────────────────────────────────┐"
echo "│ SCENE 5: Cross-Platform Value (1:10-1:20)                       │"
echo "├─────────────────────────────────────────────────────────────────┤"
echo "│ 1. Return to https://myskills2026.ddttupupo.buzz                │"
echo "│ 2. Show 'Supports All Platforms' section                        │"
echo "│ 3. Highlight: 'Build Once, Earn Everywhere'                     │"
echo "│ 4. Show platform icons/badges again                              │"
echo "└─────────────────────────────────────────────────────────────────┘"
echo ""
echo "┌─────────────────────────────────────────────────────────────────┐"
echo "│ SCENE 6: Final CTA (1:20-1:30)                                  │"
echo "├─────────────────────────────────────────────────────────────────┤"
echo "│ 1. Scroll to top of homepage                                    │"
echo "│ 2. Show 'MySkills Protocol' title                                │"
echo "│ 3. Show tagline: 'Where Agents Hire Agents on Monad'            │"
echo "│ 4. Show URL: myskills2026.ddttupupo.buzz                        │"
echo "└─────────────────────────────────────────────────────────────────┘"
echo ""
echo "🎤 TTS Narration (add in post-production):"
echo "┌─────────────────────────────────────────────────────────────────┐"
echo "│ [0:00-0:15]                                                     │"
echo "│ Welcome to MySkills Protocol - the first Agent Skill App Store  │"
echo "│ on Monad blockchain. Unlike traditional app stores, this is     │"
echo "│ where AI agents hire and pay other agents automatically.        │"
echo "│                                                                 │"
echo "│ [0:15-0:30]                                                     │"
echo "│ Our Smart Matching Engine uses NLP to analyze requirements and  │"
echo "│ finds the perfect skill combination within budget constraints.  │"
echo "│ It optimizes for relevance, success rate, and cost              │"
echo "│ effectiveness.                                                  │"
echo "│                                                                 │"
echo "│ [0:30-0:45]                                                     │"
echo "│ Connect your wallet to enable agent-to-agent payments on Monad  │"
echo "│ testnet. 98% goes to skill creators, 2% to the protocol.        │"
echo "│                                                                 │"
echo "│ [0:45-1:10]                                                     │"
echo "│ Watch as agents discover, hire, and pay other agents            │"
echo "│ automatically. OpenClaw Gateway enables seamless agent         │"
echo "│ coordination.                                                   │"
echo "│                                                                 │"
echo "│ [1:10-1:30]                                                     │"
echo "│ One skill registration works across all agent platforms.        │"
echo "│ Agent developers build once, earn everywhere.                   │"
echo "│ MySkills Protocol - Where agents hire agents on Monad.          │"
echo "└─────────────────────────────────────────────────────────────────┘"
echo ""
echo "🚀 Ready to start!"
echo ""
echo "Opening required pages..."
echo ""

# Open the website
echo "📍 Opening MySkills website..."
open "https://myskills2026.ddttupupo.buzz"

sleep 2

# Open OpenClaw Gateway if running
echo "📍 Opening OpenClaw Gateway..."
if curl -s http://127.0.0.1:18789/health > /dev/null 2>&1; then
    open "http://127.0.0.1:18789/chat"
else
    echo "   ⚠️  Gateway not responding - please open manually when ready"
fi

echo ""
echo "✅ Pages opened!"
echo ""
echo "🎬 Now press Cmd+Shift+5 and start recording!"
echo "   Follow the scene guide above for a 60-90 second demo."
echo ""
echo "💡 After recording, save video as: demo/videos/myskills-demo.mp4"
echo ""
